name: Photon NodeJS
on: [push]
jobs:
  photon-nodejs:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Assert submodules
        run: ls vendor

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.1.727

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Shadow
        run: npm install shadow-cljs

      - name: Compile Tests
        run: ./node_modules/.bin/shadow-cljs -A:test compile :test

      - name: Run Tests
        run: node out/node-tests.js

